fresh_shop/cart/urls.py
"""__author__=Zeng"""

from django.conf.urls import url

from cart import views

urlpatterns = [
    # 添加到购物车
    url(r'^add_cart/', views.add_cart, name='add_cart'),
    # 购物车
    url(r'^carts/', views.carts, name='carts'),
    # 结算
    url(r'^place_order/', views.place_order, name='place_order'),
    # 刷新价格
    url(r'^f_price/', views.f_price, name='f_price'),
    # 购物车数据
    url(r'^cart_count/', views.cart_count, name='cart_count'),
    # 修改购物车中商品的个数
    url(r'^change_goods_num/', views.change_goods_num, name='change_goods_num'),
    # 删除购物车商品
    url(r'^cart_goods_del/(\d+)/', views.cart_goods_del, name='cart_goods_del'),
]

fresh_shop/fresh_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from fresh_shop.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

fresh_shop/goods/urls.py
"""__author__=Zeng"""

from django.conf.urls import url

from goods import views

urlpatterns = [
    # 首页
    url(r'^index/', views.index, name='index'),
    # 详情页面
    url(r'^detail/(\d+)/', views.detail, name='detail'),
]

fresh_shop/user/urls.py
"""__author__=Zeng"""

from django.conf.urls import url

from user import views

urlpatterns = [
    # 注册
    url(r'^register/', views.register, name='register'),
    # 登录
    url(r'^login/', views.login, name='login'),
    # 注销
    url(r'^logout/', views.logout, name='logout'),
    # 登录验证，获取登录系统的用户
    url('is_login/', views.is_login, name='is_login'),
    # 个人信息中心
    url('user_center_info/', views.user_center_info, name='user_center_info'),
    # 全部订单
    url('user_center_order/', views.user_center_order, name='user_center_order'),
    # 收获地址
    url('user_center_site/', views.user_center_site, name='user_center_site'),
]

fresh_shop/cart/models.py
from django.db import models

from user.models import User
from goods.models import Goods


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

fresh_shop/cart/views.py
from django.shortcuts import render

from django.http import JsonResponse

from goods.models import Goods, GoodsCategory
from cart.models import ShoppingCart


def add_cart(request):
    if request.method == 'POST':
        # 加入到购物车，需判断用户是否登录
        # 1.如果登录，加入到购物车中的数据，其实就是加入到数据库中购物车列表中（设计不好的办法）
        # 2.如果登录， 加入到购物车中的数据，存储到session中（设计相对较好的方法）
        # 如果没登录，则加入到购物车的数据，是加入到session中
        # session中存储数据：商品id，商品数量，商品的选择状态
        # 如果登录，则把session中数据同步到数据库中（中间件同步数据）

        # 1.获取商品id和商品数量
        goods_id = request.POST.get('goods_id')
        goods_num = request.POST.get('goods_num')
        # 组装存到session中的数据格式
        goods_list = [goods_id, goods_num, 1]
        # {'goods': [[1,2,1], [2,5,1], [5,1,1]]}
        if request.session.get('goods'):
            # 说明session中存储了加入到购物车的商品信息
            # 判断当前加入到购物车中的数据，是否已经存在于session总
            # 如果存在，则修改session中该商品的数量
            # 如果不存在，则新增
            flag = 0
            session_goods = request.session['goods']
            for goods in session_goods:
                # 判断如果加入到购物车中数据，已经存在于session中，则修改
                if goods[0] == goods_id:
                    goods[1] = int(goods[1]) + int(goods_num)
                    flag = 1
            # 如果不存在，则添加
            if not flag:
                session_goods.append(goods_list)
            request.session['goods'] = session_goods
            goods_count = len(session_goods)
        else:
            data = []
            data.append(goods_list)
            request.session['goods'] = data
            goods_count = 1
        return JsonResponse({'code': 200, 'msg': '请求成功！', 'goods_count': goods_count})


def carts(request):
    if request.method == 'GET':
        # 如果没有登录，则从session中取商品的信息
        # 如果登录，还是从session中取数据（保证数据库中的商品和session中的商品一致）
        session_goods = request.session.get('goods')
        if session_goods:
            # 获取session中所有的商品id值
            goods_all = []
            for goods in session_goods:
                cart_goods = Goods.objects.filter(pk=goods[0]).first()
                goods_number = goods[1]
                total_price = int(goods[1]) * cart_goods.shop_price
                goods_all.append([cart_goods, goods_number, total_price])
            # 获取商品对象
            # 前提需要商品信息，商品个数，商品的总价
            # 后台返回结构[[goods objects, number, total_price], [goods objects, number, total_price]]
        else:
            goods_all = ''
        return render(request, 'cart.html', {'goods_all': goods_all})


def place_order(request):
    if request.method == 'GET':
        user_id = request.session.get('user_id')
        carts = ShoppingCart.objects.filter(user_id=user_id,
                                            is_select=1).all()
        for cart in carts:
            # 给每一个购物车商品对象添加一个total_price属性，用于存储总价
            cart.total_price = int(cart.nums) * int(cart.goods.shop_price)
        return  render(request, 'place_order.html', {'carts': carts})


def f_price(request):
    """
    返回购物车或session中商品的价格，和总价
    {key:[[id1, price1],[id2, price2]], key2: total_price}
    """
    if request.method == 'GET':
        user_id = request.session.get('user_id')
        if user_id:
            # 获取当前登录系统的用户的购物车中的数据
            carts = ShoppingCart.objects.filter(user_id=user_id)
            cart_data = {}
            cart_data['goods_price'] = [(cart.goods_id,
                                         cart.nums * cart.goods.shop_price)
                                        for cart in carts]
            all_price = 0
            # 总的价格
            for cart in carts:
                if cart.is_select:
                    all_price += cart.nums * cart.goods.shop_price
            cart_data['all_price'] = all_price
        else:
            # 拿到session中所有的商品信息,[id, num, is_select]
            session_goods = request.session.get('goods')
            # 返回数据结构，{’goods_price'：[[id1, price1],[id2, price2]...]}
            cart_data = {}
            data_all = []
            # 计算总价
            all_price = 0
            for goods in session_goods:
                data = []
                data.append(goods[0])
                g = Goods.objects.get(pk=goods[0])
                data.append(int(goods[1]) * g.shop_price)
                # 生成的data为: [id1, price1]
                data_all.append(data)
                # 判断如果商品勾选了，才计算总价格
                if goods[2]:
                    all_price += int(goods[1]) * g.shop_price
            cart_data['goods_price'] = data_all
            cart_data['all_price'] = all_price
        return JsonResponse({'code': 200, 'cart_data': cart_data})


def cart_count(request):
    if request.method == 'GET':
        # 判断购物车中商品的个数
        user_id = request.session.get('user_id')
        # 当前购物车中的商品数量
        if user_id:
            # 如果用户登录。则回去购物车表中的商品个数
            count = ShoppingCart.objects.filter(user_id=user_id).count()
        else:
            # 如果用户没有登录，则回去session中的商品个数
            session_goods = request.session.get('goods')
            count = len(session_goods) if session_goods else 0
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def change_goods_num(request):
    if request.method == 'POST':
        # 修改购物车中商品的个数
        # 1. 先判断用户登录与否，如果用户没有登录，则修改session中商品的个数
        # 2. 如果用户登录，需要判断当前修改的商品是否存在于session中，如果存在，则修改session。如果不存在则修改购物车的表
        # 获取修改的商品id，商品个数，商品选择状态
        goods_id = int(request.POST.get('goods_id'))
        goods_num = int(request.POST.get('goods_num'))
        is_select = int(request.POST.get('is_select'))

        user_id = request.session.get('user_id')

        # 先判断要修改的商品是否存在于session中，如果存在则修改session中的商品个数和选择状态
        session_goods = request.session.get('goods')
        # goods的结构为: [id1, num, is_select]
        if session_goods:
            for goods in session_goods:
                if goods_id == int(goods[0]):
                    # 修改session中商品的个数和选择状态
                    goods[1] = goods_num
                    goods[2] = is_select
            request.session['goods'] = session_goods

        # 如果用户登录了，则需要在修改购物车中数据，因为session中的商品有可能并不在购物车表中
        if user_id:
            # 修改购物车中商品个数
            ShoppingCart.objects.filter(user_id=user_id, goods_id=goods_id).update(nums=goods_num,
                                                                                   is_select=is_select)
        return JsonResponse({'code': 200, 'msg': '请求成功'})


def cart_goods_del(request, id):
    if request.method == 'POST':
        # 1.删除session中的商品
        session_goods = request.session.get('goods')
        index = 0
        for goods in session_goods:
            if goods[0] == int(id):
                break
            index +=1
        s = session_goods.pop(index)
        request.session['goods'] = session_goods
        # 2. 如果用户登录，同时也删除数据库中的商品
        user_id = request.session.get('user_id')
        if user_id:
            Goods.objects.filter(pk=id).delete()
        return JsonResponse({'code': 200, 'msg': '请求成功'})

fresh_shop/templates/base_main.html
{% extends 'base.html' %}


{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock %}


{% block js %}
	{% load static %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        <!-- 获取用户的登录用户名 -->
        $.get('/user/is_login/', function(data){
            if(data.code == '200'){
                $('.login_info em').html(data.username)
                <!--展示当前用户的信息-->
                $('.login_info').show()
                <!--隐藏登录注册按钮-->
                $('.login_btn').remove()
            }
        })

        <!-- 获取购物车中的商品个数 -->
        $.get('/cart/cart_count/', function(data){
            if(data.code == '200'){
                $('#show_count').html(data.count)
                $('.total_count em').html(data.count)
            }
        })
    </script>
{% endblock %}


{% block header %}
    {% load static %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl" style="display: none">
					欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="{%	url 'user:logout' %}">注销</a>
				</div>
				<div class="login_btn fl">
					<a href="{%	url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:carts' %}">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block search %}
	{% load static %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:carts' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count"></div>
		</div>
	</div>
{% endblock %}


{% block footer %}
	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock %}

fresh_shop/templates/index.html
{% extends 'base_main.html' %}


{% block title %}
	天天生鲜-首页
{% endblock %}


{% block js %}
    {{ block.super }}
    {% load static %}
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock %}


{% block content %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>

    {% for key,value in goods_dict.items %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">{{ key }}</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/media/{{ value.0.category.category_front_image }}"></div>
			<ul class="goods_list fl">
				{% for goods in value %}
				<li>
					<h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
					<a href="{% url 'goods:detail' goods.id %}"><img src="/media/{{ goods.goods_front_image }}"></a>
					<div class="prize">¥ {{ goods.shop_price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock %}

fresh_shop/templates/login.html
{% extends 'base_main.html' %}


{% block title %}
	天天生鲜-登录
{% endblock %}


{% block header %}
{% endblock %}

{% block search %}
{% endblock %}


{% block content %}
	{% load static %}
	<div class="login_top clearfix">
		<a href="{% url 'goods:index' %}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="" method="post">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="password" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock	%}

fresh_shop/templates/register.html
{% extends 'base_main.html' %}


{% block title %}
    天天生鲜-注册
{% endblock %}


{% block js %}
    {% load static %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock %}


{% block header %}
{% endblock %}


{% block search %}
{% endblock %}


{% block content %}
    {% load static %}
    <div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="" method="post">
                {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="username" id="user_name">
						<span class="error_tip">{{ errors }}</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="password" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpassword" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

fresh_shop/templates/user_center_info.html
{% extends 'base_main.html' %}


{% block title %}
	天天生鲜-用户中心
{% endblock %}


{% block search %}
	{% load static %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock %}


{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_info' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'user:user_center_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:user_center_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>18210569700</li>
							<li><span>联系方式：</span>18210569700</li>
							<li><span>联系地址：</span>北京市昌平区</li>			
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				<li>
					<a href="detail.html"><img src="images/goods/goods003.jpg"></a>
					<h4><a href="detail.html">大兴大棚草莓</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">16.80/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods004.jpg"></a>
					<h4><a href="#">吐鲁番梨光杏</a></h4>
					<div class="operate">
						<span class="prize">￥5.50</span>
						<span class="unit">5.50/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods005.jpg"></a>
					<h4><a href="#">黄肉桃</a></h4>
					<div class="operate">
						<span class="prize">￥10.00</span>
						<span class="unit">10.00/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods006.jpg"></a>
					<h4><a href="#">进口西梅</a></h4>
					<div class="operate">
						<span class="prize">￥28.80</span>
						<span class="unit">28.8/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods007.jpg"></a>
					<h4><a href="#">香梨</a></h4>
					<div class="operate">
						<span class="prize">￥6.45</span>
						<span class="unit">6.45/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
			</ul>
		</div>
		</div>
	</div>
{% endblock %}

fresh_shop/templates/user_center_order.html
{% extends 'base_main.html' %}


{% block title %}
	天天生鲜-用户中心
{% endblock %}


{% block search %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock %}


{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:user_center_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:user_center_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">未支付</li>		
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
				
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">已支付</li>			
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						</tr>
					</tbody>
				</table>

				<div class="pagenation">
					<a href="#"><\上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>
{% endblock %}

fresh_shop/templates/user_center_site.html
{% extends 'base_main.html' %}


{% block title %}
	天天生鲜-用户中心
{% endblock %}


{% block search %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
{% endblock %}


{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:user_center_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:user_center_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form>
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock %}